#
# © 2024-present https://github.com/cengiz-pz
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"
annotation = "1.9.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

[plugins]
android-library = { id = "com.android.library", version = "8.6.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
undercouch-download = { id = "de.undercouch.download", version = "5.6.0" }
